export const STORAGE_KEY = 'ALL_MATCHES';
export const LAST_FETCH_TIME_KEY = 'LAST_FETCH_TIME';
export const LAST_CURRENT_FETCH_TIME_KEY = 'LAST_CURRENT_FETCH_TIME';
export const ONE_HOUR_IN_MS = 60 * 60 * 1000;
export const FIFTEEN_MINUTES_IN_MS = 15 * 60 * 1000;
export const ONE_MINUTE_IN_MS = 60 * 1000;
export const THIRTY_SECONDS_IN_MS = 30 * 1000;